# Generated by Django 3.1 on 2020-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
