# Generated by Django 3.1 on 2020-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_auto_20201009_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
